# Exploring BigQuery

- BigQuery metadata, i.e. information about a table
- BigQuery query limits with QueryJobConfig()

## Setup

In [ ]:
from google.cloud import bigquery
from google.colab import auth
import pandas as pd

auth.authenticate_user()

In [ ]:
billing_project_id = 'cool-monolith-286222'

# Create client object
client = bigquery.Client(project=billing_project_id)

## Table Metadata Exploration

### List the tables

In [16]:
# Construct a reference to the "Global Biodiversity Information Facility" dataset
dataset_ref = client.dataset("gbif", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Get all the tables in the dataset
tables = list(client.list_tables(dataset))

# Print names of all tables in the dataset
for table in tables:
  print(table.table_id)

occurrences

In [17]:
table_id = "occurrences"
table_id

'occurrences'

### Look at the table schema

In [18]:
# Construct a reference to the "mobility report" table
table_ref = dataset.table("occurrences")

# API request - fetch the table
table = client.get_table(table_ref)

# See the table's schema - name, field type, mode, description
table.schema

[SchemaField('gbifid', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('datasetkey', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('occurrenceid', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('kingdom', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('phylum', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('class', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('order', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('family', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('genus', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('species', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('infraspecificepithet', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('taxonrank', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('scientificname', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('verbatimscientificname', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('verbatimscientificnameauthorship', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('countrycode', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('locality', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('stateprovince', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('occurrencestatus', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('individualcount', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('publishingorgkey', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('decimallatitude', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('decimallongitude', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('coordinateuncertaintyinmeters', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('coordinateprecision', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('elevation', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('elevationaccuracy', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('depth', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('depthaccuracy', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('eventdate', 'TIMESTAMP', 'NULLABLE', None, None, (), None),
 SchemaField('day', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('month', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('year', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('taxonkey', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('specieskey', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('basisofrecord', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('institutioncode', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('collectioncode', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('catalognumber', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('recordnumber', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('identifiedby', 'RECORD', 'NULLABLE', None, None, (SchemaField('array', 'RECORD', 'REPEATED', None, None, (SchemaField('array_element', 'STRING', 'NULLABLE', None, None, (), None),), None),), None),
 SchemaField('dateidentified', 'TIMESTAMP', 'NULLABLE', None, None, (), None),
 SchemaField('license', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('rightsholder', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('recordedby', 'RECORD', 'NULLABLE', None, None, (SchemaField('array', 'RECORD', 'REPEATED', None, None, (SchemaField('array_element', 'STRING', 'NULLABLE', None, None, (), None),), None),), None),
 SchemaField('typestatus', 'RECORD', 'NULLABLE', None, None, (SchemaField('array', 'RECORD', 'REPEATED', None, None, (SchemaField('array_element', 'STRING', 'NULLABLE', None, None, (), None),), None),), None),
 SchemaField('establishmentmeans', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('lastinterpreted', 'TIMESTAMP', 'NULLABLE', None, None, (), None),
 SchemaField('mediatype', 'RECORD', 'NULLABLE', None, None, (SchemaField('array', 'RECORD', 'REPEATED', None, None, (SchemaField('array_element', 'STRING', 'NULLABLE', None, None, (), None),), None),), None),
 SchemaField('issue', 'RECORD', 'NULLABLE', None, None, (SchemaField('array', 'RECORD', 'REPEATED', None, None, (SchemaField('array_element', 'STRING', 'NULLABLE', None, None, (), None),), None),), None)]

In [19]:
# convert the table.schema into a data frame
fields = pd.DataFrame( [ x.to_api_repr() for x in table.schema ] )
fields.head()

           name    type      mode fields
0        gbifid  STRING  NULLABLE    NaN
1    datasetkey  STRING  NULLABLE    NaN
2  occurrenceid  STRING  NULLABLE    NaN
3       kingdom  STRING  NULLABLE    NaN
4        phylum  STRING  NULLABLE    NaN

In [20]:
fields.shape

(50, 4)

In [21]:
# Preview the first five lines of the table as a data frame
client.list_rows(table, max_results=5).to_dataframe().transpose()

,0,1,2,3,4
gbifid,3599137728,3172947391,3523468642,3169999285,3693280574
datasetkey,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,4fa7b334-ce0d-4e88-aaae-2e0c138d049e
occurrenceid,URN:catalog:CLO:EBIRD:OBS1173704723,URN:catalog:CLO:EBIRD:OBS937842969,URN:catalog:CLO:EBIRD_CAN:OBS1173830660,URN:catalog:CLO:EBIRD:OBS937959988,URN:catalog:CLO:EBIRD:OBS1173990708
kingdom,Animalia,Animalia,Animalia,Animalia,Animalia
phylum,Chordata,Chordata,Chordata,Chordata,Chordata
class,Aves,Aves,Aves,Aves,Aves
order,Passeriformes,Passeriformes,Passeriformes,Passeriformes,Passeriformes
family,Corvidae,Tyrannidae,Icteridae,Mimidae,Hirundinidae
genus,Corvus,Myiarchus,Icterus,Dumetella,Stelgidopteryx
species,Corvus brachyrhynchos,Myiarchus crinitus,Icterus galbula,Dumetella carolinensis,Stelgidopteryx serripennis
infraspecificepithet,None,None,None,None,None
taxonrank,SPECIES,SPECIES,SPECIES,SPECIES,SPECIES
scientificname,"Corvus brachyrhynchos C.L.Brehm, 1822","Myiarchus crinitus (Linnaeus, 1758)","Icterus galbula (Linnaeus, 1758)","Dumetella carolinensis (Linnaeus, 1766)","Stelgidopteryx serripennis (Audubon, 1838)"
verbatimscientificname,Corvus brachyrhynchos,Myiarchus crinitus,Icterus galbula,Dumetella carolinensis,Stelgidopteryx serripennis
verbatimscientificnameauthorship,None,None,None,None,None
countrycode,US,CA,CA,US,US
locality,"Donahoo Rd, Tonganoxie US-KS (39.1577,-95.0105)",Backyard,"Atlas square 15TVP09 - Rainy River District, 1...",Irish Grove MOS Sanctuary,"Jackson Park, Chicago--Wooded Island/Bobolink ..."
stateprovince,Kansas,Ontario,Ontario,Maryland,Illinois
occurrencestatus,PRESENT,PRESENT,PRESENT,PRESENT,PRESENT
individualcount,3,1,1,1,1
publishingorgkey,e2e717bf-551a-4917-bdc9-4fa0f342c530,e2e717bf-551a-4917-bdc9-4fa0f342c530,e2e717bf-551a-4917-bdc9-4fa0f342c530,e2e717bf-551a-4917-bdc9-4fa0f342c530,e2e717bf-551a-4917-bdc9-4fa0f342c530
decimallatitude,39.157715,45.389618,48.736866,37.994404,41.785713
decimallongitude,-95.01052,-75.74444,-94.25913,-75.73026,-87.58296
coordinateuncertaintyinmeters,NaN,NaN,NaN,NaN,NaN
coordinateprecision,NaN,NaN,NaN,NaN,NaN
elevation,NaN,NaN,NaN,NaN,NaN
elevationaccuracy,NaN,NaN,NaN,NaN,NaN
depth,NaN,NaN,NaN,NaN,NaN
depthaccuracy,NaN,NaN,NaN,NaN,NaN
eventdate,2021-06-02 00:00:00+00:00,2020-06-05 00:00:00+00:00,2021-05-30 00:00:00+00:00,2020-06-01 00:00:00+00:00,2010-04-10 00:00:00+00:00
day,2,5,30,1,10
month,6,6,5,6,4
year,2021,2020,2021,2020,2010
taxonkey,2482507,2483597,2484340,2494936,2489202
specieskey,2482507,2483597,2484340,2494936,2489202
basisofrecord,HUMAN_OBSERVATION,HUMAN_OBSERVATION,HUMAN_OBSERVATION,HUMAN_OBSERVATION,HUMAN_OBSERVATION
institutioncode,CLO,CLO,CLO,CLO,CLO
collectioncode,EBIRD,EBIRD,EBIRD_CAN,EBIRD,EBIRD
catalognumber,OBS1173704723,OBS937842969,OBS1173830660,OBS937959988,OBS1173990708
recordnumber,None,None,None,None,None
identifiedby,{'array': []},{'array': []},{'array': []},{'array': []},{'array': []}
dateidentified,NaT,NaT,NaT,NaT,NaT
license,CC_BY_4_0,CC_BY_4_0,CC_BY_4_0,CC_BY_4_0,CC_BY_4_0
rightsholder,None,None,None,None,None
recordedby,{'array': [{'array_element': 'obsr684247'}]},{'array': [{'array_element': 'obsr335875'}]},{'array': [{'array_element': 'obsr766422'}]},{'array': [{'array_element': 'obsr165954'}]},{'array': [{'array_element': 'obsr1411120'}]}
typestatus,{'array': []},{'array': []},{'array': []},{'array': []},{'array': []}
establishmentmeans,None,None,None,None,None
lastinterpreted,2024-04-17 08:57:16.100000+00:00,2024-04-17 08:32:57.357000+00:00,2024-04-17 08:57:16.209000+00:00,2024-04-17 08:32:57.472000+00:00,2024-04-17 08:57:16.293000+00:00
mediatype,{'array': []},{'array': []},{'array': []},{'array': []},{'array': []}
issue,{'array': [{'array_element': 'CONTINENT_DERIVE...,{'array': [{'array_element': 'CONTINENT_DERIVE...,{'array': [{'array_element': 'CONTINENT_DERIVE...,{'array': [{'array_element': 'CONTINENT_DERIVE...,{'array': [{'array_element': 'CONTINENT_DERIVE...

##  Add safe config settings

BigQuery allows you to query up to 1 TB per month. You can quickly reach this limit if you are not careful. Luckily, there are ways to assess and limit the amount of data you are querying.

Set constants for sizes

In [22]:
ONE_MB = 1_000*1_000
ONE_GB = 1_000*ONE_MB

### Sample Queries - Dry Run

You can use a 'dry run' to estimate the size of a query before running it.

In [23]:
project_id = "bigquery-public-data"
dataset_id = "gbif"
table_id = "occurrences"

queries = []

queries += [ f"""
        SELECT countrycode
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE class = "Magnoliopsida" AND countrycode ='US'
        LIMIT 10
        """ ]

queries += [ f"""
        SELECT countrycode
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE class = "Magnoliopsida" AND countrycode ='US'
        """ ]

queries += [ f"""
        SELECT countrycode
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE countrycode ='US'
        """ ]

queries += [ f"""
        SELECT year
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE year = 2012
        """ ]

queries += [ f"""
        SELECT countrycode, class
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE class = "Magnoliopsida" AND countrycode ='US'
        """ ]

queries += [ f"""
        SELECT countrycode, class
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE countrycode ='US'
        """ ]

queries += [ f"""
        SELECT countrycode, class
        FROM {project_id}.{dataset_id}.{table_id}
        """ ]

queries += [ f"""
        SELECT countrycode
        FROM {project_id}.{dataset_id}.{table_id}
        """ ]

queries += [ f"""
        SELECT count(countrycode)
        FROM {project_id}.{dataset_id}.{table_id}
        """ ]

queries += [ f"""
        SELECT count(1)
        FROM {project_id}.{dataset_id}.{table_id}
        """ ]

queries += [ f"""
        SELECT count(countrycode)
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE countrycode ='US'
        """ ]

queries += [ f"""
        SELECT count(1)
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE countrycode ='US'
        """ ]

len(queries)

12

In [24]:
for query in queries:
  dry_run_config = bigquery.QueryJobConfig(dry_run = True)
  dry_run_query_job = client.query(query, job_config= dry_run_config)
  size = dry_run_query_job.total_bytes_processed
  print(query)
  print(f"{size:_}")
  print()

        SELECT countrycode
        FROM bigquery-public-data.gbif.occurrences
        WHERE class = "Magnoliopsida" AND countrycode ='US'
        LIMIT 10

35_002_295_626


        SELECT countrycode
        FROM bigquery-public-data.gbif.occurrences
        WHERE class = "Magnoliopsida" AND countrycode ='US'

35_002_295_626


        SELECT countrycode
        FROM bigquery-public-data.gbif.occurrences
        WHERE countrycode ='US'

11_685_171_796


        SELECT year
        FROM bigquery-public-data.gbif.occurrences
        WHERE year = 2012

22_694_457_936


        SELECT countrycode, class
        FROM bigquery-public-data.gbif.occurrences
        WHERE class = "Magnoliopsida" AND countrycode ='US'

35_002_295_626


        SELECT countrycode, class
        FROM bigquery-public-data.gbif.occurrences
        WHERE countrycode ='US'

35_002_295_626


        SELECT countrycode, class
        FROM bigquery-public-data.gbif.occurrences

35_002_295_626


        SELECT countrycode
        FROM bigquery-public-data.gbif.occurrences

11_685_171_796


        SELECT count(countrycode)
        FROM bigquery-public-data.gbif.occurrences

11_685_171_796


        SELECT count(1)
        FROM bigquery-public-data.gbif.occurrences

0


        SELECT count(countrycode)
        FROM bigquery-public-data.gbif.occurrences
        WHERE countrycode ='US'

11_685_171_796


        SELECT count(1)
        FROM bigquery-public-data.gbif.occurrences
        WHERE countrycode ='US'

11_685_171_796

Sample Query 1 - Safe Config
You can also specify a limit for how much data you want to scan.

In [25]:
# Create a list of queries
queries = []

queries += [ f"""
        SELECT count(1) as `total`
        FROM {project_id}.{dataset_id}.{table_id}
        """ ]

queries += [ f"""
        SELECT count(1) as `total`
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE countrycode ='US'
        """ ]

queries += [ f"""
        SELECT count(countrycode) as `total`
        FROM {project_id}.{dataset_id}.{table_id}
        """ ]

queries += [ f"""
        SELECT count(countrycode) as `total`
        FROM {project_id}.{dataset_id}.{table_id}
        WHERE countrycode ='US'
        """ ]

len(queries)

4

In [32]:
# safe_config needs to be included with every client.query() request
safe_config = bigquery.QueryJobConfig(
    maximum_bytes_billed=ONE_GB,
    # totalBytesProcessed=ONE_GB,
    # total_bytes_processed=ONE_GB,
)
# Use a try...except block to catch when the safe_config paramenter prevents a query
for query in queries:
  print(query)
  try:
    df = client.query(query, job_config=safe_config).to_dataframe()
    print(df.head())
  except:
    print("Blocked by safe_config")

        SELECT count(1) as `total`
        FROM bigquery-public-data.gbif.occurrences

        total
0  2961438667

        SELECT count(1) as `total`
        FROM bigquery-public-data.gbif.occurrences
        WHERE countrycode ='US'

        total
0  1088444124

        SELECT count(countrycode) as `total`
        FROM bigquery-public-data.gbif.occurrences

        total
0  2921292949

        SELECT count(countrycode) as `total`
        FROM bigquery-public-data.gbif.occurrences
        WHERE countrycode ='US'

        total
0  1088444124

In [33]:
f"{ONE_GB:_}"

'1_000_000_000'

In [34]:
2669694827 > ONE_GB

True